name: Build Wine
on:
  push:
    branches:
      - main

jobs:
  build_wine:
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - run: uname -a
      - run: git submodule update --init --recursive

      - name: Cache homebrew
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/Homebrew
            /usr/local/Homebrew
            /usr/local/Cellar
            /usr/local/Caskroom
            /usr/local/bin
            /usr/local/etc
            /usr/local/include
            /usr/local/lib
            /usr/local/opt
            /usr/local/sbin
            /usr/local/share
            /usr/local/var
            /opt/homebrew
          key: brew-${{ runner.os }}-${{ hashFiles('**/build.sh') }}
          restore-keys: |
            brew-${{ runner.os }}-

      - name: Setup homebrew
        run: /bin/sh init_brew.sh

      - name: Build and install dependencies
        run: INSTALL=1 /bin/sh build_inotify_kqueue.sh

      - name: Build wine
        run: /bin/sh build.sh /Users/runner/wine-build-artifacts

      - name: Run wineboot
        run: |
          cd /Users/runner/wine-build-artifacts
          WINEPREFIX=/Users/runner/wine-build-artifacts DYLD_FALLBACK_LIBRARY_PATH="/usr/local/lib/" time ./bin/wine wineboot -u

      # https://github.com/actions/upload-artifact/issues/192#issuecomment-1375651018
      - name: Prepare files
        run: |
          mkdir ./tmp
          sudo cp -r /Users/runner/wine-build-artifacts ./tmp
          sudo chown -R runner:runner ./tmp

      - name: Upload wine build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wine-build-artifacts
          path: ./tmp
