name: Build Crossover Wine 25
on:
  push:
    branches:
      - main

jobs:
  build_wine:
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - run: uname -a

      - name: Cache Homebrew
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/Homebrew
            /usr/local/Homebrew
            /usr/local/Cellar
            /usr/local/Caskroom
            /usr/local/bin
            /usr/local/etc
            /usr/local/include
            /usr/local/lib
            /usr/local/opt
            /usr/local/sbin
            /usr/local/share
            /usr/local/var
            /opt/homebrew
          key: brew-${{ runner.os }}-${{ hashFiles('**/build.sh') }}
          restore-keys: |
            brew-${{ runner.os }}-

      - name: Build Wine
        run: /bin/sh build.sh

      - name: Display directory structure
        run: |
          echo "Current directory:"
          ls -la
          echo "Sources directory:"
          ls -la sources/ || echo "No sources directory"
          echo "Wine directory:"
          ls -la sources/wine/ || echo "No sources/wine directory"
          echo "Wine program files:"
          find sources/wine/ -name "*.exe" -o -name "*.dll" | head -20

      - name: Upload wine build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wine-build-artifacts
          path: |
            sources/wine/dlls/**/*.dll
            sources/wine/programs/**/*.exe
            sources/wine/programs/**/*.dll
            sources/wine/loader/*.exe
            sources/wine/server/wineserver
            sources/wine/*.so
